- name: Call handler
  shell: ls
  notify:
    - HandlerOne

- name: Test handler
  # ansible.builtin.import_tasks: include.yaml
  ansible.builtin.include_tasks: "include.yaml"

- name: Task
  debug:
    msg: "最后一个任务"