all:
  children:
    ungrouped: {}
    test:
      hosts:
        hw-cloud-xngy-jump-server-linux-2:
          ansible_host: 192.168.0.249
          ansible_port: 10022
      vars:
        ansible_become: "yes"
        ansible_become_password: ""
        ansible_password: ""
        ansible_user: lichenhao
    tj_test:
      hosts:
        tj-test-spst-lichenhao:
          ansible_host: 172.38.180.212
          ansible_port: 22
      vars:
        ansible_user: root
        ansible_password: ""
