- name: 检查文件是否存在
  block:
    - name: Get stats of the File
      ansible.builtin.stat:
        path: /etc/os-release
      register: file_stat

    - name: Print a debug message
      ansible.builtin.debug:
        msg: "文件存在，大小为：{{file_stat.stat.size}}"
      when: file_stat.stat.exists == true

    - name: Print a debug message
      ansible.builtin.debug:
        msg: "文件不存在"
      when: file_stat.stat.exists == false
  tags:
    - check_file_exist
