- hosts: test
  tasks:
    - debug:
        msg: "{{f1|to_nice_yaml(indent=2)}}"
      vars:
        f1:
          father: "Bob"
          mother: "Alice"
          Children:
            - Judy
            - Tedy
